logLevel=INFO
disableSystemOut=false
maxExpectations=100
maxLogEntries=500
enableCORSForAPI=true
enableCORSForAllResponses=true
corsAllowOrigin=*
corsAllowHeaders=Allow, Content-Encoding, Content-Length, Content-Type, ETag, Authorization, X-Pix-Signature, X-Pix-Event, X-Pix-Timestamp, X-Pix-EndToEndId
corsAllowMethods=CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE
